### ISSUE TITLE
digitaltrends.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#697] opened 2019-02-20 02:12 UTC
### Basic Information

**Test link:** `https://www.digitaltrends.com/computing/amd-driver-update-adds-power-plan-for-optimized-performance/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3702.0 Safari/537.36
**Extension:** Nano Defender 15.0.0.93

**Comment by okiehsch** [comment] 2019-02-20 02:36
Duplicate of https://github.com/NanoMeow/QuickReports/issues/692

**Comment by NanoMeow** [comment] 2019-02-21 04:06
### Basic Information

**Test link:** `https://www.digitaltrends.com/computing/macbook-pro-keyboard-failure-rate-double-older-models/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
**Extension:** Nano Defender 15.0.0.93

### Additional Message

**Comment by jspenguin2017** [comment] 2019-02-23 05:28
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/53282161-2ce90e00-36f1-11e9-8e51-1b67a0244582.png)

**Comment by NanoMeow** [comment] 2019-03-21 04:42
### Basic Information

**Test link:** `https://www.digitaltrends.com/computing/best-torrent-clients/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

### Additional Message

They got me man!

**Comment by jspenguin2017** [comment] 2019-03-21 04:43
Still works fine for me.

**Comment by NanoMeow** [comment] 2019-04-10 01:13
### Basic Information

**Test link:** `https://www.digitaltrends.com/computing/how-to-record-your-computer-screen/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.124

### Additional Message

**Comment by jspenguin2017** [comment] 2019-04-10 01:15
@okiehsch This broke. 
![image](https://user-images.githubusercontent.com/7283682/55844699-dba7a900-5afb-11e9-9caf-bb2125c49618.png)

**Comment by NanoMeow** [comment] 2019-04-12 01:23
### Basic Information

**Test link:** `https://www.digitaltrends.com/cool-tech/we-spoke-to-an-mit-computer-scientists-about-the-simulation-hypothesis/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.125

### Additional Message

**Comment by okiehsch** [comment] 2019-04-12 01:53
> @okiehsch This broke.

https://github.com/uBlockOrigin/uAssets/issues/5320

**Closed** 2019-04-12 03:01 UTC
Labels: s: backlog, s: dispatched, t: anti-adblock
