### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2537] opened 2019-12-21 19:03 UTC
### Basic Information

**Test link:** `https://twitter.com/search?q=xiaozhan&src=recent_search_click`
**Category:** ads
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

`https://blog.inflationdata.com/what-are-central-banks/?utm_source=taboola`

This window keeps popping up wherever I browse Twitter even with pop-ups blocked.

**Comment by NanoMeow** [comment] 2020-04-17 15:15
### Basic Information

**Test link:** `https://twitter.com/home`
**Category:** breakage
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

It's blocking all Images and Video's.

**Comment by NanoMeow** [comment] 2020-04-17 15:15
### Basic Information

**Test link:** `https://twitter.com/Rosincaxpearl/status/1250955061687181313`
**Category:** breakage
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36 Edg/81.0.416.53
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

video not playing

**Comment by DandelionSprout** [comment] 2020-04-18 15:42
Twitter seems to have rolled out a redesign to a random amount of users in the past week, making the two recentmost reports very difficult to test.

**Comment by jspenguin2017** [comment] 2020-04-18 18:36
Twitter is working fine for me, refreshed many times, marking as works for now.

**Comment by llacb47** [comment] 2020-04-18 18:38
@DandelionSprout I've had the redesign for 3-4 months. Maybe it's a regional rollout.

**Comment by DandelionSprout** [comment] 2020-04-18 18:40
If it's the recentmost redesign where the Home button is now on the left of the timeline instead of above it, then I thank you for confirming that it works well.

**Comment by llacb47** [comment] 2020-04-18 18:44
Yeah, but the DOM is a lot uglier. All the class names are gibberish and it's harder to write rules. :(

**Comment by jspenguin2017** [comment] 2020-04-18 18:46
Yea, the home button is on the left for me for a while now, never had any issues.

**Comment by NanoMeow** [comment] 2020-05-19 22:31
### Basic Information

**Test link:** `https://twitter.com/rDragaliaLost`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

promoted tweets placeholder not completely cleaned out
may require account

**Comment by jspenguin2017** [comment] 2020-05-19 22:49
Requires account to reproduce. Also this looks quite difficult to fix.

**Comment by llacb47** [comment] 2020-05-20 00:04
Here are some very ugly rules - all three are needed to totally eliminate the placeholder. 

However, on a site like twitter CSS hiding rules might have an adverse effect on performance. 
```
twitter.com##div:has(>div>div>h2[role="heading"]:has-text(/推荐|Promoted|Gesponsert|Реклама|Promocionado|Sponsorisé|Uitgelicht|プロモーション/))
twitter.com##div:has(>div>div>div>h2[role="heading"]:has-text(/推荐|Promoted|Gesponsert|Реклама|Promocionado|Sponsorisé|Uitgelicht|プロモーション/))+div:has(>div>div)
twitter.com##div[aria-label*=" - "]>div[style^="padding-"]>div[style^="padding-"]>div:has(article)+div:has(>div>div:empty):not(+div+div:has(h2[role="heading"]))
```

**Closed** 2020-05-20 03:35 UTC
Labels: f: resolved, t: placeholders

**Comment by llacb47** [comment] 2020-05-23 20:27
It looks like there's still one unblocked: `https://twitter.com/candicebroce`
