### ISSUE TITLE
sprysphere.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3231] opened 2020-03-06 16:51 UTC
### Basic Information

**Test link:** `
http://sprysphere.com/BiZZ`
**Category:** other
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.87 Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

See: `https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/12#note_300130822`

**Comment by jspenguin2017** [comment] 2020-03-07 02:47
@lain566 said on Mar 5, 2020: 

> I know this has nothing to do with Hulu, but, Does this commit fix adfly notifications?
`https://github.com/jspenguin2017/uBlockProtector/commit/591c8769b6fa4a68cbc85b34633372da930774e8`
>
> I just tried and I'm still stuck, however I tried the Adguard scriptlet they got from uBO and it works fine 
`https://github.com/AdguardTeam/Scriptlets/blob/master/src/scriptlets/prevent-adfly.js`
>
> I tried it with this link
`http://sprysphere.com/BiZZ` and I was immediately redirected to dropbox.com
>
> What's the difference between the two?

**Comment by jspenguin2017** [comment] 2020-03-07 02:48
@lain566 said on Mar 5, 2020: 

> I know this has nothing to do with [redacted], but, Does this commit fix adfly notifications?
`https://github.com/jspenguin2017/uBlockProtector/commit/591c8769b6fa4a68cbc85b34633372da930774e8`
>
> I just tried and I'm still stuck, however I tried the Adguard scriptlet they got from uBO and it works fine 
`https://github.com/AdguardTeam/Scriptlets/blob/master/src/scriptlets/prevent-adfly.js`
>
> I tried it with this link
`http://sprysphere.com/BiZZ` and I was immediately redirected to dropbox.com
>
> What's the difference between the two?

**Comment by jspenguin2017** [comment] 2020-03-07 02:59
@lain566 

The change is to address https://github.com/jspenguin2017/uBlockProtector/issues/1104 , it has nothing to do with the issue related to notifications. 

I checked AdGuard's code, it is based on uAssets' code which is in turn based on ND's code. I don't believe anyone made any meaningful changes to the code for almost a year, so there isn't really any major differences between AdGuard's code and ND's code right now. 

I tried to change ND's code to exactly match AdGuard's code, but I still get the notification popup, so I think AdGuard is bypassing the notification in some other ways.

**Comment by jspenguin2017** [comment] 2020-03-07 03:01
Merging this into the current issue in Nano Filters repository. 

See: https://github.com/NanoAdblocker/NanoFilters/issues/370

**Comment by lain566** [comment] 2020-03-07 09:45
@jspenguin2017 Thanks for checking, this confirms my doubts, so, I have done a little research, and yes, I know what is the filter that makes the redirection immediate, are two filters.
I have added an exception to disable those filters, and the result is the same as with uBO.

I already knew those filters, but I didn't care, because at that time I had no problems with redirection, and I couldn't reproduce this issue.

So, if you have opened this issue, for my question in gitlab, then this issue can be closed and marked as Solved, you are the right person to answer this type of question, after all the script code is yours from the beginning and your answer has cleared my doubts, and as I see many open issues on this topic, if you want we can continue the discussion here https://github.com/NanoAdblocker/NanoFilters/issues/370 for example.

**Comment by jspenguin2017** [comment] 2020-03-07 19:41
Yea, please continue the discussion in https://github.com/NanoAdblocker/NanoFilters/issues/370 . This issue will be left open to not confuse the bots.

**Comment by jspenguin2017** [comment] 2020-03-08 19:32
Fix available in the next version of ND.

**Closed** 2020-03-08 19:32 UTC
Labels: f: resolved, t: ads
