### ISSUE TITLE
watchparksandrecreation.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1658] opened 2019-08-13 01:19 UTC
### Basic Information

**Test link:** `https://watchparksandrecreation.net/watch/parks-and-recreation-6x18/`
**Category:** ads
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

**Comment by okiehsch** [comment] 2019-08-13 01:57
https://github.com/uBlockOrigin/uAssets/commit/7a9e4a0eea5171b002e610e7f6dcd86e22cb93af

**Comment by llacb47** [comment] 2019-08-13 02:30
Pop-ups

**Comment by jspenguin2017** [comment] 2019-08-13 02:48
There's a leftover close button on the top left corner, might as well fix that? 

I can't reproduce popup though.

**Comment by okiehsch** [comment] 2019-08-13 02:50
Popups are fixed on my end by the filter I added in the referenced commit.

**Comment by okiehsch** [comment] 2019-08-13 02:52
Fixed the leftover.

**Closed** 2019-08-13 02:52 UTC
Labels: s: backlog, s: dispatched, t: ads
