### ISSUE TITLE
space.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2086] opened 2019-10-20 19:00 UTC
### Basic Information

**Test link:** `https://www.space.com/`
**Category:** anti-adblock
**Reported from:** Hungary
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

Original URL: `https://www.space.com/cc.html`

**Comment by NanoMeow** [comment] 2019-11-01 15:05
### Basic Information

**Test link:** `https://www.space.com/halloween-space-pumpkin-nasa-jpl-contest-2019.html?utm_source=Selligent&utm_medium=email&utm_campaign=9486&utm_content=20191031_SDC_Newsletter+-+adhoc+&utm_term=3488476&m_i=Y78%2BKqQ5cvlnkfQP_V2GHfTmPZaZ8UtqqrqIuNfSjT2eyX_1mLvf7LbGx9BVCyElRfXU8zbdLETlvhzVCM1eaO1fl2QUYWYYY3`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

**Comment by NanoMeow** [comment] 2019-11-09 23:42
### Basic Information

**Test link:** `https://www.space.com/astronaut-chris-cassidy-prepares-space-station-journey.html?utm_source=Selligent&utm_medium=email&utm_campaign=9885&utm_content=20191109_SDC_Newsletter+-+adhoc+&utm_term=3488476&m_i=ql0PZELwi9iwVVYrW2TjpNjfCNwuOq7aSSDYEyX%2BAOOk6kRraC7WnDJviodF%2By9iwkneQ_4enb_TynZ36HdZsvaXFx4bwDaOqm`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

**Comment by NanoMeow** [comment] 2019-12-08 21:33
### Basic Information

**Test link:** `https://www.space.com/space-station-ams-repair-third-spacewalk.html?utm_source=Selligent&utm_medium=email&utm_campaign=11072&utm_content=20191208_SDC_Newsletter+-+adhoc_2+&utm_term=3488476&m_i=ehGe459uijWM3pUtJ5XBGm2TldvcBFCu5zJ7DS7VkxHwWLwf8a9FPaWctHh5kFiHaZsSClQocrwV%2BGauTCnvnpcxM5MPvpUNej`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

**Comment by NanoMeow** [comment] 2020-01-17 00:08
### Basic Information

**Test link:** `https://www.space.com/15421-black-holes-facts-formation-discovery-sdcmp.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

Original URL: `https://github.com/easylist/easylist/issues`

It told me that it found my adblocker
isnt nano defender supposed to remove that?

**Comment by llacb47** [comment] 2020-01-17 00:54
`space.com##+js(aopr, _sp_._networkListenerData)`

Or, preferable solution IMO, using network filters:

```
||futurecdn.net^*/header.js$script,3p
||space.com^*space-gb.js$script,redirect=noop.js
||space.com^*space-gb.js$xhr,redirect=noop.txt
```

This reduces the number of blocked requests from around 60 to about 10.

**Comment by jspenguin2017** [comment] 2020-01-17 23:37
Can't reproduce, it works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/72653352-b0ce6900-3947-11ea-9bdd-24a5c35b164d.png)

**Comment by llacb47** [comment] 2020-01-18 01:05
it happens sporadically. try incognito/clearing cookies

**Comment by jspenguin2017** [comment] 2020-01-18 02:35
Tried incognito mode, refreshed multiple times, can't reproduce.

**Comment by llacb47** [comment] 2020-01-18 03:14
Fix is only in uBo annoyances - without it: `https://streamable.com/x0mj7`

**Comment by jspenguin2017** [comment] 2020-01-18 03:33
The video sometimes takes a bit to load. I think the issue is just annoyance (so won't be fixed in default uBO).

**Comment by NanoMeow** [comment] 2020-05-31 15:01
### Basic Information

**Test link:** `https://www.space.com/28445-spacex-elon-musk-drone-ships-names.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Defender 15.0.0.199

### Additional Message

**Comment by jspenguin2017** [comment] 2020-06-01 01:43
Can't reproduce anti-adblock. Placeholder fixed.

**Closed by jspenguin2017** 2020-06-01 01:43 UTC
Labels: f: resolved, t: placeholders
