### ISSUE TITLE
t66y.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1203] opened 2019-05-12 04:22 UTC
### Basic Information

**Test link:** `http://t66y.com/htm_data/2/1905/3523046.html`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.27 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

nsfw sticky
https://github.com/NanoAdblocker/NanoFilters/issues/317

**Comment by NanoMeow** [comment] 2019-06-18 01:01
### Basic Information

**Test link:** `http://t66y.com/htm_data/7/1906/3554653.html`
**Category:** anti-adblock
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0
**Extension:** Nano Defender 15.0.0.153

### Additional Message

**Comment by llacb47** [comment] 2019-08-03 17:33
Can't reproduce, however if you click on an image you are taken to a URL like `https://www.viidii.info/?action=image&url=https%3A%2F%2Fwww.skeimg.com%2Fi%2F%3Fi%3Du%2F20190606%2F20000517.jpg&src=https%3A%2F%2Fwww.skeimg.com%2Fu%2F20190606%2F20000517.jpg` that has ads fixed by Easylist China. Then, the page linked at the top (`https://www.skeimg.com/i/?i=u/20190606/20000517.jpg`) has popups.

**Comment by jspenguin2017** [comment] 2019-08-03 17:42
@okiehsch Popup reproduced as per instructions above. 

@llacb47 Hum... Maybe it's not sticky anymore.

**Comment by okiehsch** [comment] 2019-08-04 01:47
Fixed.

**Closed** 2019-08-04 01:58 UTC
Labels: f: resolved, nsfw, t: ads
