### ISSUE TITLE
thingiverse.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4598] opened 2020-08-29 19:28 UTC
### Basic Information

**Test link:** `https://www.thingiverse.com/thing:2305162`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

**Comment by okiehsch** [comment] 2020-08-29 23:46
Already fixed in annoyances. https://github.com/uBlockOrigin/uAssets/commit/8d76b7008cd1ca7a5d268e8a27d1db94d8b10a18

**Comment by jspenguin2017** [comment] 2020-08-30 01:41
@okiehsch Why is this annoyance? It prevents you from downloading the files.

**Comment by okiehsch** [comment] 2020-08-30 01:48
I get the warning but the download starts after 5 seconds on my end.
![image](https://user-images.githubusercontent.com/16838044/91649372-a5adf080-ea73-11ea-8b5e-bcd434403ddb.png)

**Comment by jspenguin2017** [comment] 2020-08-30 02:01
It looks like if I close the popup within the 5 seconds then it breaks... Never mind then... 

But the timer would be considered ads, not annoyance, right?

**Comment by okiehsch** [comment] 2020-08-30 02:04
You mean moving
`thingiverse.com##+js(nano-sib)`
to `uBO-filters`.
I agree.

**Comment by jspenguin2017** [comment] 2020-08-30 02:05
Yep, that's what I meant.

**Comment by okiehsch** [comment] 2020-08-30 02:06
Fixed.

**Closed** 2020-08-30 02:12 UTC
Labels: f: resolved, t: ads, t: anti-adblock

**Comment by jspenguin2017** [comment] 2020-08-30 02:15
Actually it looks like the timer only breaks when the anti-adblock is triggered. But it's more of a bug on their side instead of functionality limitation.

**Comment by okiehsch** [comment] 2020-08-30 02:27
I can reproduce after reloading, it always works on the first page load for me but after that it breaks on my end too until I open a new tab.

I agree that it is probably a bug on their side but the end result is that adblock users can only download once and then are left wondering why it does not work.
I will move the fix to `uBO-filters` after all, sorry for the back and forth.
