### ISSUE TITLE
userupload.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3240] opened 2020-03-07 20:03 UTC
### Basic Information

**Test link:** `https://userupload.net/tu0ucuku0j18`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.191

**Comment by llacb47** [comment] 2020-03-08 03:17
Can't reproduce

**Comment by jspenguin2017** [comment] 2020-03-08 17:43
Can't reproduce anti-adblock. 

---

Has bundled download, unsure if it can be fixed with filters.

**Comment by ghajini** [comment] 2020-03-08 19:32
Bundled download removed like this

`userupload.net##+js(remove-attr, checked, #addon )`
`userupload.net##.mb-4.custom-checkbox.text-center.custom-control`

**Comment by jspenguin2017** [comment] 2020-03-09 00:02
@okiehsch

**Closed** 2020-04-13 19:04 UTC
Labels: f: resolved, t: other
