### ISSUE TITLE
globalnews.ca

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1324] opened 2019-06-01 21:42 UTC
### Basic Information

**Test link:** `https://globalnews.ca/news/5340854/virginia-beach-mass-shooting/?utm_source=Other&utm_medium=MostPopular&utm_campaign=2014`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.112

### Additional Message

ads placeholders

**Comment by jspenguin2017** [comment] 2019-06-01 21:43
Ads placeholders.

**Comment by NanoMeow** [comment] 2019-07-09 01:01
### Basic Information

**Test link:** `https://globalnews.ca/news/5472851/us-iran-tension-impact-canadian-troops-iraq/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

### Additional Message

"AD BLOCKER DETECTED: Advertising revenue employs Canadian journalists in your local community. By choosing to view ads you help support their work." Yes, it goes away when you click "Continue watching" but there's always space to improve `¯\_(ツ)_/¯`

Reported by `@austinhuang0131`

**Comment by jspenguin2017** [comment] 2019-07-09 01:02
Can't reproduce anti-adblock.

**Comment by NanoMeow** [comment] 2019-12-18 02:09
### Basic Information

**Test link:** `https://globalnews.ca/video/6310466/new-twist-on-prepaid-gift-card-scam-costs-alberta-couple-200`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

anti-adblock every couple videos

**Comment by jspenguin2017** [comment] 2019-12-18 02:09
@okiehsch Annoyance.

**Comment by okiehsch** [comment] 2019-12-18 02:14
I can't reproduce the videos play fine on my end.

**Comment by jspenguin2017** [comment] 2019-12-18 02:19
Looks like it's fixed in the annoyance filter already, my bad, forgot to test. It does leave big ads placeholders though, add: `globalnews.ca##.ad-container`

**Comment by okiehsch** [comment] 2019-12-18 02:22
Added.

**Comment by jspenguin2017** [comment] 2019-12-18 02:38
The rest of ads placeholders are already fixed in Placeholder Buster filters.

**Closed** 2019-12-18 02:38 UTC
Labels: f: resolved, t: anti-adblock
