### ISSUE TITLE
opensubtitles.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#561] opened 2019-01-12 23:34 UTC
### Basic Information

**Test link:** `https://www.opensubtitles.org/en/search/subs`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/2018.11 Safari/537.36 Chrome/71.0.0.0
**Extension:** Nano Defender 15.0.0.81

**Comment by okiehsch** [comment] 2019-01-13 04:37
Fixed in annoyances.

**Comment by jspenguin2017** [comment] 2019-01-13 17:52
I can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/51088786-55a8db80-1721-11e9-9a11-2f07484f4ddf.png)

**Comment by okiehsch** [comment] 2019-01-13 19:51
Happens on every second reload on my end.
![image](https://user-images.githubusercontent.com/16838044/51089912-c4635480-1774-11e9-9706-4c636573eb6e.png)

**Comment by NanoMeow** [comment] 2019-11-08 16:21
### Basic Information

**Test link:** `https://www.opensubtitles.org/pb`
**Category:** breakage
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

Changing website language does not work with Nano enabled.

**Closed** 2019-11-09 04:34 UTC
Labels: f: resolved, t: breakage
