### ISSUE TITLE
patorjack.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2003] opened 2019-10-07 18:14 UTC
### Basic Information

**Test link:** `https://patorjack.com/sheila-snow-is-back/`
**Category:** anti-adblock
**Reported from:** Philippines
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

**Comment by okiehsch** [comment] 2019-10-07 22:31
NSFW and I can't reproduce.

**Comment by jspenguin2017** [comment] 2019-10-07 22:34
Can't reproduce anti-adblock. Has ads placeholders.

**Comment by okiehsch** [comment] 2019-10-07 22:38
The anti-adblock issue is fixed in `uAssets` for the site with a generichide filter.
Does
`patorjack.com##.spot`
fix all placeholders?

**Comment by jspenguin2017** [comment] 2019-10-08 00:06
Maybe also these? 
```
patorjack.com##.adsright
patorjack.com##.refill:has(:scope > .spots)
```

**Comment by okiehsch** [comment] 2019-10-08 00:12
Added.

**Comment by okiehsch** [comment] 2019-10-08 00:12
That was quick. ;)

**Closed** 2019-10-08 00:12 UTC
Labels: nsfw, s: backlog, s: dispatched, t: ads
