### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#415] opened 2018-12-07 13:33 UTC
### Basic Information

**Test link:** `https://shinden.pl/external-video/52111-banana-fish/view/167599`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
**Extension:** Nano Defender 15.0.0.80

### Additional Message

not working rly

**Comment by jspenguin2017** [comment] 2018-12-11 15:18
Fixed in Polish regional filters.

**Comment by NanoMeow** [comment] 2019-02-08 03:31
### Basic Information

**Test link:** `https://shinden.pl/episode/12825-uchuu-senkan-yamato-2199/view/99601#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

**Comment by jspenguin2017** [comment] 2019-02-08 03:32
Still works fine with Polish regional filters enabled.

**Comment by NanoMeow** [comment] 2019-04-06 17:56
### Basic Information

**Test link:** `https://shinden.pl/episode/12710-sword-art-online/view/99004?r307=1`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.101

### Additional Message

shinden.pl

**Comment by jspenguin2017** [comment] 2019-04-06 17:56
Still works fine with Polish regional filters enabled.

**Comment by NanoMeow** [comment] 2019-04-06 17:57
### Basic Information

**Test link:** `https://shinden.pl/episode/3325-darker-than-black-kuro-no-keiyakusha/view/30949`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36 Vivaldi/2.4.1488.35
**Extension:** Nano Defender 15.0.0.121

### Additional Message

Login and password:
http://bugmenot.com/view/shinden.pl

**Comment by NanoMeow** [comment] 2019-04-06 18:01
### Basic Information

**Test link:** `https://shinden.pl/episode/45192-kimi-no-na-wa/view/135510`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.121

### Additional Message

**Comment by NanoMeow** [comment] 2019-04-09 01:27
### Basic Information

**Test link:** `https://shinden.pl/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Original URL: `https://shinden.pl/episode/54177-dororo/view/171276`

That site block nano adblocker ;C

**Comment by NanoMeow** [comment] 2019-04-12 01:21
### Basic Information

**Test link:** `https://shinden.pl/episode/7431-fullmetal-alchemist-brotherhood/view/64504#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

**Comment by NanoMeow** [comment] 2019-04-12 01:25
### Basic Information

**Test link:** `https://shinden.pl/episode/45192-kimi-no-na-wa/view/135510#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.125

### Additional Message

The website detects adblock after clicking "pokaż" button

**Comment by NanoMeow** [comment] 2019-04-12 01:25
### Basic Information

**Test link:** `https://shinden.pl/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Nano defender + nano adblocker is detected

**Comment by NanoMeow** [comment] 2019-04-19 02:42
### Basic Information

**Test link:** `https://shinden.pl/episode/50362-youjo-senki-recap/view/158048#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.129

### Additional Message

**Comment by NanoMeow** [comment] 2019-04-20 16:54
### Basic Information

**Test link:** `https://shinden.pl/episode/51100-tate-no-yuusha-no-nariagari/view/160140#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.133

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

After clicking on player site is detecting an adblock and dont allow me to watch.
Im using nano adblocker with newest filters and nano defender

**Comment by NanoMeow** [comment] 2019-04-23 01:20
### Basic Information

**Test link:** `https://shinden.pl/episode/10-monster/view/398#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.104

### Additional Message

**Comment by NanoMeow** [comment] 2019-04-26 01:38
### Basic Information

**Test link:** `https://shinden.pl/episode/16156-noragami/view/116852`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

Strona znów wykrywa adblocka.

**Comment by NanoMeow** [comment] 2019-05-04 00:46
### Basic Information

**Test link:** `https://shinden.pl/episode/54177-dororo/view/179165#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.105

### Additional Message

**Comment by NanoMeow** [comment] 2019-05-04 00:46
### Basic Information

**Test link:** `https://shinden.pl/episode/35763-jojo-s-bizarre-adventure-stardust-crusaders-2nd-season/view/127007#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.139

### Additional Message

you need to be logged in to check itm an anti-adblock showing up

**Comment by jspenguin2017** [comment] 2019-05-04 00:48
Maybe requires account, otherwise cannot reproduce any issue when Polish regional filters are enabled.

**Comment by Fantazyjny** [comment] 2019-05-05 13:04
Yes, account is required:
Login: bugmenot
PW: bugmenot

**Comment by jspenguin2017** [comment] 2019-05-05 17:08
I don't see any issues when Polish regional filters are enabled. 
![image](https://user-images.githubusercontent.com/7283682/57197568-21eaff00-6f26-11e9-87eb-b5883a40de20.png)

**Comment by Fantazyjny** [comment] 2019-05-05 18:38
That's strange. You should have list of available video services with episode but you don't have any.
It should look like this:
![2019-05-05](https://user-images.githubusercontent.com/8149819/57198418-dca0ee80-6f72-11e9-8f0c-8fd63b65026a.png)

After clicking on "Pokaż" there will be message with adblock detection.
![2019-05-05 (2)](https://user-images.githubusercontent.com/8149819/57198644-65b92500-6f75-11e9-946a-3e19d238401e.png)


Are you trying on "bugmenot" or bugmenot123" account? Because on "bugmenot123" I don't see any streaming services like on screen shot made by you.

**Comment by jspenguin2017** [comment] 2019-05-05 18:58
I'm using the `bugmenot / bugmenot` account. Maybe it's GeoLock. I don't have a Polish VPN right now.

**Comment by jspenguin2017** [comment] 2019-05-05 18:59
@olegwukr FYI.

**Comment by Fantazyjny** [comment] 2019-05-05 21:45
I'm reading Shinden forum and looks like it is "geolocked".
From forum:
Chrome: 
Go to chrome://settings/languages

1.

**Comment by jspenguin2017** [comment] 2019-05-05 22:18
Ah, OK, I see the issue now. 

@okiehsch FYI.

**Comment by NanoMeow** [comment] 2019-05-07 01:22
### Basic Information

**Test link:** `https://shinden.pl/episode/54042-nande-koko-ni-sensei-ga/view/179796#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Adblocker 1.0.0.105

### Additional Message

**Comment by NanoMeow** [comment] 2019-05-07 01:23
### Basic Information

**Test link:** `https://shinden.pl/episode/54177-dororo/view/179169#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.106

### Additional Message

anti - ad block do not work :C

**Comment by okiehsch** [comment] 2019-05-07 01:36
I get a 404 error at all posted links, so I can't help.

**Comment by kulfoon** [comment] 2019-05-08 08:15
Fantazyjny: as for tha main Anti-Adblock & Click-Popup are you aware of this thread https://github.com/MajkiIT/polish-ads-filter/issues/12976 it contains the solution.

**Comment by jspenguin2017** [comment] 2019-05-09 01:10
I would guess both are generated by https://github.com/javascript-obfuscator/javascript-obfuscator

**Comment by garggul** [comment] 2019-05-10 11:02
This man found a working scriplet solution:

>  lain566: https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-491094068

**Comment by NanoMeow** [comment] 2019-05-15 02:28
### Basic Information

**Test link:** `https://shinden.pl/episode/12710-sword-art-online/view/99004#column-one-inner`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.145

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#known-issues`

I use Ublock to blocks advertising , and i want to use this on shinden.pl but  their blocks my ublock origin ssoo i mean if i use nano defender there cant block then (no) there block always , i paste scripts to my ublock but nothing 


shinden.pl Blocks Ublock origin + Nano defender doesn't work on this host https://zapodaj.net/aecabab7eab52.png.html  <--- Screean shot

**Comment by jspenguin2017** [comment] 2019-05-15 02:29
See also: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/42

**Comment by jspenguin2017** [comment] 2019-05-20 00:36
Issue in regional filter is closed.

**Closed by jspenguin2017** 2019-05-20 00:36 UTC
Labels: f: resolved, nsfw, t: anti-adblock
