### ISSUE TITLE
derstandard.at

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#42] opened 2018-08-29 13:12 UTC
### Basic Information

**Test link:** `https://derstandard.at/2000086210054-1223/US-Astronom-Williams-Da-draussen-muss-es-Leben-geben`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.40

**Comment by jspenguin2017** [comment] 2018-08-29 13:13
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/149

**Comment by NanoMeow** [comment] 2018-11-25 18:07
### Basic Information

**Test link:** `https://derstandard.at/`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.77 Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.75

### Additional Message

**Comment by NanoMeow** [comment] 2018-11-25 19:55
### Basic Information

**Test link:** `https://derstandard.at/`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.75

### Additional Message

Page is not accessible when Nano  Adblocker and Nano Defender is running :(

**Comment by jspenguin2017** [comment] 2018-11-25 19:56
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/48983865-79508d80-f0b1-11e8-9008-4f5ba8ba71b1.png)

**Comment by jspenguin2017** [comment] 2018-11-25 19:57
I can't reproduce any other problems beside refreshing the home page 5 times may trigger anti-adblock (which shouldn't happen in normal use).

**Comment by NanoMeow** [comment] 2019-02-07 01:58
### Basic Information

**Test link:** `https://derstandard.at/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

**Comment by NanoMeow** [comment] 2019-02-28 02:05
### Basic Information

**Test link:** `https://derstandard.at/`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.120 Safari/537.36 Vivaldi/2.3.1440.57
**Extension:** Nano Defender 15.0.0.102

### Additional Message

anti-adblock kicks in after a few page impressions using nano adblocker + defender. deleting the MGUID cookie fixes the issue temporarily

**Comment by jspenguin2017** [comment] 2019-02-28 02:13
@okiehsch I can now reproduce the issue by navigating over 5 to 10 random articles. Can you test again? 
![image](https://user-images.githubusercontent.com/7283682/53536464-c6366c80-3ac3-11e9-9766-092e054a3e5f.png)

**Comment by okiehsch** [comment] 2019-02-28 02:21
After navigating randomly 15 times

![image](https://user-images.githubusercontent.com/16838044/53536798-fa338100-3b07-11e9-96d2-493cd69014b7.png)

![image](https://user-images.githubusercontent.com/16838044/53536754-d8d29500-3b07-11e9-8672-f3418d2a27f3.png)

**Comment by okiehsch** [comment] 2019-02-28 02:34
OK, I tried with a fresh profile and the message shows up.

**Comment by okiehsch** [comment] 2019-02-28 02:35
The suggested filter works for me, can you confirm?

**Comment by jspenguin2017** [comment] 2019-02-28 03:29
That breaks login, right?

**Comment by okiehsch** [comment] 2019-02-28 03:39
Yes.

**Comment by okiehsch** [comment] 2019-02-28 04:25
Does
````
@@||ad1.adfarm1.adition.com/s$script,domain=derstandard.at
@@||derstandard.nuggad.net/rc$script,domain=derstandard.at
derstandard.at##.Werberahmen
derstandard.at##.topBanner
````
work for you?

**Comment by jspenguin2017** [comment] 2019-02-28 04:33
Yea, I'd say it's good enough. 

The anti-adblock screen still come up sometimes, but goes away after a little bit.

**Comment by okiehsch** [comment] 2019-02-28 04:36
Added.

**Closed** 2019-02-28 04:38 UTC
Labels: f: resolved, t: anti-adblock
