### ISSUE TITLE
hypebeast.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4257] opened 2020-07-05 23:23 UTC
### Basic Information

**Test link:** `https://hypebeast.com/tags/Vans-Era-Pro`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Defender for Firefox 15.0.0.200

**Comment by okiehsch** [comment] 2020-07-06 00:55
@jspenguin2017 
I can't reproduce consistently.
Is it a hard block or an annoyance on your end?
`hypebeast.com##+js(nostif, ad-block-popup)`
should work.

**Comment by llacb47** [comment] 2020-07-06 01:22
It's a annoyance - dismissable popup.

According to the duration of the cookie `adblockpop` set upon closing, it will come back every two days.

**Comment by okiehsch** [comment] 2020-07-06 02:22
@llacb47 thx.
Fixed.

**Comment by jspenguin2017** [comment] 2020-07-07 02:52
I don't see a close button for the popup, but it goes away upon refresh.

**Comment by jspenguin2017** [comment] 2020-07-07 02:52
@okiehsch I don't see a close button for the popup, but it goes away upon refresh. Can be considered annoyance I guess...

**Closed by jspenguin2017** 2020-07-07 02:52 UTC
Labels: f: resolved, t: anti-adblock

**Comment by okiehsch** [comment] 2020-07-07 02:56
![image](https://user-images.githubusercontent.com/16838044/86696805-16a1d080-c00e-11ea-9500-3f406e6891dd.png)

Clicking the X closes it.

**Comment by jspenguin2017** [comment] 2020-07-07 03:23
Strange, maybe it works differently in dark theme? 
![image](https://user-images.githubusercontent.com/7283682/86701105-f69eec80-bfce-11ea-8abc-945a2b596924.png)

**Comment by okiehsch** [comment] 2020-07-07 03:47
No.
![image](https://user-images.githubusercontent.com/16838044/86704573-51f3cd80-c015-11ea-96ca-ad4928f243ec.png)

**Comment by jspenguin2017** [comment] 2020-07-07 14:23
Huh, could be some A/B testing going on.
