### ISSUE TITLE
quizlet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#35] opened 2018-08-28 01:19 UTC
### Basic Information

**Test link:** `https://quizlet.com`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.39

### Additional Message

Doesn't prevent use of website but asks you to upgrade.

**Comment by llacb47** [comment] 2019-08-03 19:39
Test link: `https://quizlet.com/321912915/physics-flash-cards/`

In sidebar.

**Comment by jspenguin2017** [comment] 2019-08-03 21:26
Ads placeholders removed. Can't reproduce other issues, closing for now.

**Closed by jspenguin2017** 2019-08-03 21:26 UTC
Labels: f: resolved, t: ads
