### ISSUE TITLE
calciomercato.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2134] opened 2019-10-26 03:35 UTC
### Basic Information

**Test link:** `https://www.calciomercato.com/news/quattro-anni-di-donnarumma-ma-il-futuro-resta-un-rebus-il-piano--89584`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

On below of every news, It appears this message:

You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.

**Comment by mapx-** [comment] 2019-10-26 07:18
annoyance => enable `uBlock filters – Annoyances` list

**Comment by jspenguin2017** [comment] 2019-10-26 15:52
I can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/67622292-47bad780-f7d6-11e9-9fca-e05bf2c114ac.png)

**Comment by NanoMeow** [comment] 2019-11-16 02:50
### Basic Information

**Test link:** `https://www.calciomercato.com/news/l-italia-da-lezioni-di-bel-calcio-non-teme-nessuno-e-all-europeo-29847`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

On the entire website, https://www.calciomercato.com, there are anti ad-block messages.

**Comment by jspenguin2017** [comment] 2019-11-16 02:53
@okiehsch Fixed by annoyance filter but this is hard now.

**Comment by jspenguin2017** [comment] 2019-11-16 02:53
Also has some ads placeholders.

**Comment by okiehsch** [comment] 2019-11-16 03:04
Fixed.

**Closed** 2019-11-16 15:31 UTC
Labels: f: resolved, t: ads, t: anti-adblock
