### ISSUE TITLE
foodnetwork.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#189] opened 2018-10-11 22:17 UTC
### Basic Information

**Test link:** `https://www.foodnetwork.com/recipes/food-network-kitchen/banana-walnut-bread-recipe-2011439`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.55

### Additional Message

Large banner whining about ad blocker

**Comment by jspenguin2017** [comment] 2018-10-13 17:59
@okiehsch Annoyance, caught in FAB generic solution in ND. 
![image](https://user-images.githubusercontent.com/7283682/46908401-7cb3ff00-cedf-11e8-96d1-042de0499dbd.png)

**Comment by okiehsch** [comment] 2018-10-13 18:02
I can't reproduce.

**Comment by jspenguin2017** [comment] 2018-10-13 18:02
Also: `foodnetwork.com##body:style(margin-top: 0px !important;)`

**Comment by jspenguin2017** [comment] 2018-10-13 18:04
Oh, NVM, the anti-adblock is already fixed in the annoyance filter.

**Comment by NanoMeow** [comment] 2018-11-12 02:31
### Basic Information

**Test link:** `https://www.foodnetwork.com/search/grill-turkey-leg-`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.72

### Additional Message

Blocker msg at the bottom

**Closed** 2018-12-21 17:56 UTC
Labels: f: resolved, t: ads
