### ISSUE TITLE
stltoday.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1368] opened 2019-06-11 01:35 UTC
### Basic Information

**Test link:** `https://www.stltoday.com/news/national/fire-department-helicopter-crash-reported-in-manhattan/article_ed720041-20cc-5918-a1d1-ed6d9491c7e4.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
**Extension:** Nano Defender 15.0.0.150

**Comment by jspenguin2017** [comment] 2019-06-11 01:38
Soft anti-adblock. 

@okiehsch FYI.

**Comment by okiehsch** [comment] 2019-06-11 01:47
Is this not fixed by
![image](https://user-images.githubusercontent.com/16838044/59237735-91c26880-8bfb-11e9-9b4e-8e980ff3ace2.png)
on your end?
I can't reproduce an additional anti-adblock message.

**Comment by llacb47** [comment] 2019-06-11 02:19
I still see [this](https://user-images.githubusercontent.com/16567977/59238894-af78d900-8bcd-11e9-9ef7-bfe0e030ae2e.jpg) message.

**Comment by okiehsch** [comment] 2019-06-11 02:22
Hm, I don't.
Is it still there if you add
`@@||stltoday.com^$generichide`

**Comment by llacb47** [comment] 2019-06-11 02:34
Doesn't seem to be

**Comment by okiehsch** [comment] 2019-06-11 02:42
@jspenguin2017 if you see the same message can you chekc if we can simply hide it?

**Comment by jspenguin2017** [comment] 2019-06-11 02:47
This works for me: 
```
@@||stltoday.com^$generichide
stltoday.com##.tnt-ads-container
stltoday.com##.dfp-ad
```

**Comment by okiehsch** [comment] 2019-06-11 02:50
I will add it to `uBO-filters`.
Seems to me like the message is caused by 
`||fundingchoicesmessages.google.com^$domain=stltoday.com`
in `uBO-filters`.

**Comment by okiehsch** [comment] 2019-06-11 02:52
Fixed.

**Closed** 2019-06-11 02:53 UTC
Labels: f: resolved, t: anti-adblock
