### ISSUE TITLE
animepahe.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3746] opened 2020-05-03 15:07 UTC
### Basic Information

**Test link:** `https://animepahe.com/play/2ac0db47-7835-3be8-44c4-400d330abf76/fd0dd3e4af75ad7fc12cd8730589e5c920a47424895f98a607ed2c89f54bbff4`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

spams adblocker and overloads browser

**Comment by jspenguin2017** [comment] 2020-05-04 00:53
I can't reproduce any problems, the website has no ads and does not have performance issues.

**Comment by jspenguin2017** [comment] 2020-05-04 00:54
I can't reproduce any problems, the website does not have anti-adblock nor performance issues.

**Comment by okiehsch** [comment] 2020-05-04 03:11
Try using Chromium block all third-party requests and see the "undefined" requests.
We have a discussion in slack about this new PopAds script.

**Comment by okiehsch** [comment] 2020-05-04 03:40
By the way I can see a window opening and closing immediately at that domain on the first page load, though the logger does not indicate any popup has happened on my end.
It is caused by `https://www.xadsmart.com/sails.io.min.js`
Adding `animepahe.com##+js(aopr, PopAds)` fixes that issue on my end.

**Comment by okiehsch** [comment] 2020-05-04 03:47
I think the opening window is caused by `https://xadsmart.com/Rn.asp?_=e1&v=4&pSfNAOnd=&minBid=&iChlNGgm=0,0&XdzQTrAW=&kwgTCMvH=&s=1920,1080,1,1920,1080,0`
I don't know what 
````
window._pao.parse({'result': 0, 'url': ''});
````
does.

**Comment by okiehsch** [comment] 2020-05-04 03:52
I think the opening window is caused by `https://xadsmart.com/Rn.asp?_=e1&v=4&pSfNAOnd=&minBid`
I don't know what
`window._pao.parse({'result': 0, 'url': ''});`
does.
Maybe the window closes immediately because that script does not declare any url. 😕

**Closed** 2020-05-04 14:55 UTC
Labels: f: works
