### ISSUE TITLE
flashx.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1592] opened 2019-07-30 02:18 UTC
### Basic Information

**Test link:** `https://www.flashx.tv/pairing.php`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

**Comment by llacb47** [comment] 2019-07-31 01:43
Can't reproduce, requires account. Here are the credentials for a throwaway disposable account you can use to test:
Username: `nevonibuvu`
Password: `nevonibuvu@best-mail.net`

There are also popups/popunders on player pages as well.

**Comment by jspenguin2017** [comment] 2019-07-31 01:54
Hum... The website is broken because Coinhive is already dead. 

I can reproduce popup though, @okiehsch do you think it's worth fixing?

**Comment by okiehsch** [comment] 2019-07-31 02:04
I can't reproduce any popups.

**Comment by llacb47** [comment] 2019-07-31 02:07
Try here: `https://www.flashx.pw/70bw14nsl6f7.html`

Also annoyance timer.

**Comment by okiehsch** [comment] 2019-07-31 02:12
No popups and I get
![image](https://user-images.githubusercontent.com/16838044/62178421-4e59c000-b349-11e9-9eb1-88c75f7355ba.png)
so I can't continue to the video to test any further.

**Comment by llacb47** [comment] 2019-07-31 02:22
How about this: `https://watchepisodes.mrunlock.space/game-of-thrones-season-8-episode-2-s08e02__13942152`

**Comment by okiehsch** [comment] 2019-07-31 02:29
I get the same "wrong IP" message if I click the flashx link and try to get to the video.

I will fix `watchepisodes.mrunlock.space`.

**Comment by jspenguin2017** [comment] 2019-07-31 03:13
Hum... I'm still seeing a popup. Although it's auto-closed quickly. 
![image](https://user-images.githubusercontent.com/7283682/62180920-c35bd400-b30e-11e9-82b9-16686c570af2.png)

Considering the page is already broken, I'm not sure if it's worth trying to fix it.

**Comment by okiehsch** [comment] 2019-07-31 03:19
Your logs make no sense to me.
It looks like 
`flashx.*##+js(abort-on-property-write, Fingerprint2)`
does not work on your end for whatever reason.

**Comment by jspenguin2017** [comment] 2019-07-31 03:45
No, it's working, I checked in the console. 
Either way doesn't matter, the webpage isn't usable anyway.

**Comment by okiehsch** [comment] 2019-07-31 03:47
Well, those image and xhr requests in your log  are pulled by the admaven inline-script which 
`flashx.*##+js(abort-on-property-write, Fingerprint2)`
aborts on my end.
I can reproduce your log if I remove that filter.

**Comment by jspenguin2017** [comment] 2019-07-31 03:47
Hum... Could be race condition.

**Comment by okiehsch** [comment] 2019-07-31 03:53
> Could be race condition.

Possible though I tried with Firefox, Chromium and Chrome and the admaven script is succesfully aborted every time.
There are also quite a few scripts before the admavenone in the soirce on my end, so it seems unlikely to me.

**Comment by llacb47** [comment] 2019-07-31 23:56
@okiehsch Duplicate domains of `watchepisodes.mrunlock.space`: `watchepisodes4.com` which is a redirect from `watchepisodes.com`

**Comment by okiehsch** [comment] 2019-08-01 00:46
I get no popups at `watchepisodes4.com`.

**Comment by NanoMeow** [comment] 2020-05-07 19:01
### Basic Information

**Test link:** `https://www.flashx.tv/d101064ee701778bcc50298f0f394326.jsp`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

unblocked `zfgloaded` inline script

**Closed** 2020-05-08 17:49 UTC
Labels: f: resolved, t: ads
