### ISSUE TITLE
nytimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#90] opened 2018-09-14 12:40 UTC
### Basic Information

**Test link:** `https://www.nytimes.com/2018/09/13/nyregion/andrew-cuomo-cynthia-nixon-wins-governors-race.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

### Additional Message

Detects anti-adblock

**Comment by mapx-** [comment] 2018-09-14 14:45
Could you test:
`nytimes.com##:xpath(//div[contains(text(),"Advertising")]/../..)`

**Comment by ZaphodBeebblebrox** [comment] 2018-09-14 19:32
This is fixed in the uBlock Annoyances.
https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt#L639

**Comment by jspenguin2017** [comment] 2018-09-14 21:07
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/45575211-ed5bf300-b82f-11e8-8419-97c77d3d0e61.png)

**Comment by NanoMeow** [comment] 2018-09-15 16:13
### Basic Information

**Test link:** `https://www.nytimes.com/2018/09/14/nyregion/evelyn-rodriguez-kayla-cuevas-mother-killed.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

### Additional Message

**Comment by NanoMeow** [comment] 2018-09-28 17:07
### Basic Information

**Test link:** `https://www.nytimes.com/2018/09/27/opinion/republicans-affordable-care-act-hypocrisy.html`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.47

### Additional Message

Adblock is identified.
Thank you for your effort

**Comment by jspenguin2017** [comment] 2018-09-28 23:35
Can't reproduce, still works perfectly fine for me. Checked multiple articles.

**Comment by jspenguin2017** [comment] 2018-09-30 22:29
Had to clear cookies.

**Closed** 2018-09-30 22:28 UTC
Labels: anti-adblock, resolved
