### ISSUE TITLE
floridatravellife.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1923] opened 2019-09-26 15:21 UTC
### Basic Information

**Test link:** `https://www.floridatravellife.com/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

g00 crap on firefox

**Comment by mapx-** [comment] 2019-09-26 15:50
I cannot reproduce the issue using european / us ip

**Comment by llacb47** [comment] 2019-09-26 18:54
There is g00 stuff but it should be fixed in uBlock filters.

**Comment by llacb47** [comment] 2019-09-26 19:00
Although there is one crap beacon getting through...

can you add `.com/g00/*$other,1p` to uAssets?

**Closed** 2019-09-26 21:07 UTC
Labels: f: resolved, t: ads

**Comment by okiehsch** [comment] 2019-09-26 22:05
`Copyright In​start Wed Sep 18 2019 - All rights reserved - version: 10.9.23`

A new version. 

How about
`/g00/*_$/$/*$other,1p`
to ensure that it  works on all TLD's.
