### ISSUE TITLE
forbes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3414] opened 2020-03-27 14:51 UTC
### Basic Information

**Test link:** `https://www.forbes.com/sites/advisor/2020/03/26/what-to-do-about-your-student-loans-during-the-coronavirus-covid-19-crisis/#61e326bf1509`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

**Comment by krystian3w** [comment] 2020-03-31 16:27
I see only cookie "wall" (problematic).

**Comment by jspenguin2017** [comment] 2020-04-01 15:51
Can't reproduce anti-adblock. 
![image](https://user-images.githubusercontent.com/7283682/78158347-58fbb600-73fe-11ea-9f5c-85ee245726c5.png)

**Comment by jspenguin2017** [comment] 2020-04-01 15:52
The cookie wall gives the user a choice, so it will not be fixed in NanoFilters.

**Comment by NanoMeow** [comment] 2020-04-08 23:10
### Basic Information

**Test link:** `https://www.forbes.com/sites/bensin/2020/04/08/mi-10-pro-review-xiaomis-first-true-premium-flagship/#776039391a05`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

### Additional Message

detecting ad blocker

**Comment by jspenguin2017** [comment] 2020-04-09 13:23
Still can't reproduce anti-adblock.

**Comment by NanoMeow** [comment] 2020-04-15 22:11
### Basic Information

**Test link:** `https://www.forbes.com/sites/shaharziv/2020/04/14/why-are-rich-americans-getting-17-million-stimulus-checks/#cb9bdf7665b4`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

**Comment by jspenguin2017** [comment] 2020-04-16 15:54
Still works fine for me.

**Comment by krystian3w** [comment] 2020-04-16 20:20
Maybe generichide is bad (I suppose 🇺🇸  subscribe more than stock lists for uBO/Nano Adblocker)?

**Comment by jspenguin2017** [comment] 2020-04-16 20:39
This works fine on default setup. The website is in English, so its users should not have any regional filters enabled.

**Comment by NanoMeow** [comment] 2020-04-25 15:46
### Basic Information

**Test link:** `https://www.forbes.com/sites/zackomalleygreenburg/2020/04/24/kanye-west-is-now-officially-a-billionaireand-he-really-wants-the-world-to-know/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

placeholder `forbes.com##p:has(br)`

**Comment by krystian3w** [comment] 2020-04-25 16:02
maybe:
```
forbes.com##p:has(+ fbs-ad)
forbes.com##fbs-ad + p:has(br)
```

2 of 7 `p with br` not have ad as  `neighbour`.

**Closed** 2020-04-25 19:02 UTC
Labels: f: resolved, t: placeholders
