### ISSUE TITLE
freecourseweb.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1601] opened 2019-08-01 01:19 UTC
### Basic Information

**Test link:** `https://freecourseweb.com/`
**Category:** anti-adblock
**Reported from:** Hungary
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.157

### Additional Message

Site loads initially but then displays BlockAdblock message

**Comment by llacb47** [comment] 2019-08-01 01:26
Can't reproduce... maybe `freecourseweb.com##+js(bab-defuser.js)`

**Comment by jspenguin2017** [comment] 2019-08-01 03:01
Can't reproduce anti-adblock. Has a few ads placeholders though.

**Comment by littdown** [comment] 2019-08-01 11:33
Seems to have some conflicts with Ghostery addon in Firefox. If Ghostery is enabled, I can reproduce the anti-adblock message. If Ghostery is disabled, everything works fine.

**Comment by jspenguin2017** [comment] 2019-08-02 03:24
Extension conflicts are out of scope. Won't fix.

**Comment by NanoMeow** [comment] 2019-09-05 18:28
### Basic Information

**Test link:** `https://freecourseweb.com/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.167

### Additional Message

BlockAdblock still there when I use alongside Nano Adblock or built-in Slimjet Adblocker via Nano Defender though

**Comment by jspenguin2017** [comment] 2019-09-05 21:09
Can't reproduce anti-adblock. Fixed ads placeholders.

**Closed by jspenguin2017** 2019-09-05 21:09 UTC
Labels: f: resolved, t: ads
