### ISSUE TITLE
rjno1.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2223] opened 2019-11-05 22:23 UTC
### Basic Information

**Test link:** `https://www.rjno1.com/`
**Category:** breakage
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.16 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

**Comment by jspenguin2017** [comment] 2019-11-05 22:25
@okiehsch Breakage caused by Chinese regional filters. 

---

Also has a few ads placeholders (not sure if regional filters catches them).

**Comment by okiehsch** [comment] 2019-11-05 22:46
`||rjno1.com^$csp=script-src 'self' *;style-src,badfilter`
fixes the anti adblock warning but maybe that causes ads to appear?
I can't tell.

**Comment by jspenguin2017** [comment] 2019-11-05 23:04
The rule in regional filters breaks CSS. There is no anti-adblock when regional filters are disabled. I don't see any ads when regional filters are disabled, just a few placeholders.

**Comment by okiehsch** [comment] 2019-11-05 23:07
Anybody know who to ping for the regional Chinese filter?

**Comment by jspenguin2017** [comment] 2019-11-06 01:20
Placeholder on homepage and article fixed in the NanoContrib.

**Closed** 2019-11-06 01:21 UTC
Labels: f: resolved, t: ads, t: breakage

**Comment by jspenguin2017** [comment] 2019-11-06 01:22
I think EasyList China only has a forum (`http://abpchina.org/forum/forum.php`). The forum doesn't support HTTPS so I'm not sure if it's still being maintained.
