### ISSUE TITLE
timesheraldonline.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1399] opened 2019-06-21 02:39 UTC
### Basic Information

**Test link:** `https://www.timesheraldonline.com/2019/06/19/gas-main-break-shuts-sonoma-boulevard/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.115

### Additional Message

Anti-adblock detector on this newspaper website as well as all the other papers handled by this newspaper company: `https://www.medianewsgroup.com/our-brands/`  They all seem to have the same anti-adblock.

**Comment by jspenguin2017** [comment] 2019-06-21 03:34
@okiehsch Hard anti-adblock. 
![image](https://user-images.githubusercontent.com/7283682/59895781-17d07300-93a3-11e9-9530-1be7923a5f29.png)

**Comment by jspenguin2017** [comment] 2019-06-21 03:35
Tried a few other domains, can't reproduce. Closing for now.

**Comment by okiehsch** [comment] 2019-06-21 03:35
My commit beat your comment by a few seconds. ;)

**Comment by okiehsch** [comment] 2019-06-21 03:38
> Tried a few other domains in the list, can't reproduce. Closing for now.

There are quite a few `##+js(set-constant.js, CnnXt.Event.fire, noopFunc)` sites in `uBO-filters` already.

**Comment by okiehsch** [comment] 2019-06-21 03:42
Can you reopen? I found one that needs the same filter I will test more oín the next few days.

**Comment by okiehsch** [comment] 2019-06-24 01:20
You can close the issue.

**Closed** 2019-06-24 01:43 UTC
Labels: s: backlog, s: dispatched, t: anti-adblock
