### ISSUE TITLE
crazyhd.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2500] opened 2019-12-15 17:19 UTC
### Basic Information

**Test link:** `https://www.crazyhd.com/`
**Category:** anti-adblock
**Reported from:** Bangladesh
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

Original URL: `https://www.chd4.com/index.php`

CrazyHD is a popular Bangladeshi private torrent site. Nanodefender can't defuse anti-adblock of this site. Have to disable nanoadblock to browse this website.

**Comment by llacb47** [comment] 2019-12-16 01:38
Can't reproduce anti-adblock.

**Comment by masud365** [comment] 2019-12-16 13:13
Problem solved with filter `@@||chd4.com^$generichide`
Web-domain change after login from crazyhd to chd4. 
Close the issue please. Thank you for quick response. [https://github.com/NanoAdblocker/NanoFilters/issues/176](url)

**Closed** 2019-12-16 14:13 UTC
Labels: f: resolved, t: anti-adblock
