### ISSUE TITLE
dailymail.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1616] opened 2019-08-03 05:51 UTC
### Basic Information

**Test link:** `https://www.dailymail.co.uk/health/index.html`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.157

### Additional Message

Installed as per instructions, but the Daily site always seems to be step ahead.

**Comment by llacb47** [comment] 2019-08-03 18:22
Can't reproduce, maybe regional but I doubt it.

**Comment by jspenguin2017** [comment] 2019-08-03 21:19
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/62416992-1b8e2100-b602-11e9-895f-0b4d41cf123b.png)

**Comment by NanoMeow** [comment] 2019-09-10 01:02
### Basic Information

**Test link:** `https://www.dailymail.co.uk`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Original URL: `https://www.dailymail.co.uk/news/article-7445533/Boris-Johnson-rages-yellow-belly-Jeremy-Corbyn-BLOCKING-election-call.html`

Dailymail is detecting adblocker

**Comment by jspenguin2017** [comment] 2019-09-10 01:03
Has ads placeholders, but can't reproduce anti-adblock.

**Comment by NanoMeow** [comment] 2019-09-28 14:33
### Basic Information

**Test link:** `https://www.dailymail.co.uk`
**Category:** anti-adblock
**Reported from:** Slovenia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Original URL: `https://www.dailymail.co.uk/sciencetech/article-5178531/MIT-creates-bioluminescent-trees-glow-like-fireflies.html`

**Comment by jspenguin2017** [comment] 2019-09-28 14:34
For https://github.com/NanoMeow/QuickReports/issues/1616 : 
Still can't reproduce anti-adblock.

**Comment by mapx-** [comment] 2019-09-28 14:43
Who is still getting anti adb stuff should try:
`||dailymail.co.uk/static/mol-adverts/demo/next-release/*/mol-adverts.js$script`

**Comment by NanoMeow** [comment] 2019-10-21 02:39
### Basic Information

**Test link:** `https://www.dailymail.co.uk/news/article-7591439/Video-shows-moment-hero-coach-disarms-Parkrose-High-School-gunman-hugging-him.html?fbclid=IwAR03BZSw7-afbUUrmY24iIQuhJ0TYxw62sybdXPhthjKHDg8s9AdzVR2IkI`
**Category:** anti-adblock
**Reported from:** Finland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 OPR/64.0.3417.61
**Extension:** Nano Defender 15.0.0.168

### Additional Message

**Comment by jspenguin2017** [comment] 2019-10-21 22:26
For https://github.com/NanoMeow/QuickReports/issues/1616#issuecomment-544326680 : 
Still works fine for me.

**Comment by NanoMeow** [comment] 2019-10-24 16:53
### Basic Information

**Test link:** `https://www.dailymail.co.uk/home/index.html`
**Category:** anti-adblock
**Reported from:** Saudi Arabia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

**Comment by jspenguin2017** [comment] 2019-10-24 20:46
For https://github.com/NanoMeow/QuickReports/issues/1616#issuecomment-546007651 : 
Works fine with latest filters.

**Comment by NanoMeow** [comment] 2019-10-25 15:03
### Basic Information

**Test link:** `https://www.dailymail.co.uk/video/news/video-1948608/NYC-commuters-randomly-sing-Backstreet-Boys-subway-car.html`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

**Comment by jspenguin2017** [comment] 2019-10-25 22:59
For https://github.com/NanoMeow/QuickReports/issues/1616#issuecomment-546390737 : 
Still can't reproduce anti-adblock.

**Comment by NanoMeow** [comment] 2019-11-06 16:24
### Basic Information

**Test link:** `https://www.dailymail.co.uk/news/article-7652231/Nearly-200-WWE-wrestlers-crew-held-hostage-Saudi-Arabia.html`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

**Comment by jspenguin2017** [comment] 2019-11-07 04:20
For https://github.com/NanoMeow/QuickReports/issues/1616#issuecomment-550387278 : 
Still can't reproduce anti-adblock.

**Comment by NanoMeow** [comment] 2019-11-08 16:21
### Basic Information

**Test link:** `https://www.dailymail.co.uk/news/article-7663721/Trapped-shoppers-spend-night-Sheffields-Meadowhall-shopping-centre.html`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.2.14
**Extension:** Nano Defender 15.0.0.169

### Additional Message

Detects using an adblock and shows a banner and blocks from viewing the articles :(

**Comment by jspenguin2017** [comment] 2019-11-09 04:32
For https://github.com/NanoMeow/QuickReports/issues/1616#issuecomment-551892979 : 
Still can't reproduce anti-adblock.

**Comment by NanoMeow** [comment] 2019-11-20 16:43
### Basic Information

**Test link:** `https://www.dailymail.co.uk/news/article-2250725/Banker-Raphael-Geys-sacked-successful-line-multi-million-payout-winning-Supreme-Court-fight-employer.html`
**Category:** ads
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

**Comment by jspenguin2017** [comment] 2019-11-21 22:22
For https://github.com/NanoMeow/QuickReports/issues/1616#issuecomment-556092405 : 
Still can't reproduce anti-adblock.

**Comment by NanoMeow** [comment] 2019-12-10 15:40
### Basic Information

**Test link:** `https://www.dailymail.co.uk/sport/football/article-7772705/Man-Utd-tell-Ole-Gunnar-Solskjaer-job-safe-wont-Mauricio-Pochettino.html?fbclid=IwAR3uO57dPFygkD6Xsbw4TyQnVHZcInLkW4Gg_wtqNmsH5EvD63LQolFHwEc`
**Category:** anti-adblock
**Reported from:** Estonia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

**Comment by jspenguin2017** [comment] 2019-12-12 15:55
For https://github.com/NanoMeow/QuickReports/issues/1616#issuecomment-564092381 : 
Still can't reproduce anti-adblock.

**Comment by NanoMeow** [comment] 2019-12-25 04:04
### Basic Information

**Test link:** `https://www.dailymail.co.uk/home/index.html`
**Category:** ads
**Reported from:** Unknown
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

**Comment by jspenguin2017** [comment] 2019-12-25 04:06
For https://github.com/NanoMeow/QuickReports/issues/1616#issuecomment-568833578 : 
Can't reproduce.

**Comment by NanoMeow** [comment] 2020-01-23 16:39
### Basic Information

**Test link:** `https://www.dailymail.co.uk/news/article-7917413/Democrats-start-prosecuting-House-impeachment-managers-tell-senators-want-Trump-removed.html`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Defender 15.0.0.177

### Additional Message

There is a strange issue that I had for months on Daily Mail. On the articles, there are often videos. Months ago the videos stopped loading and would present just text where they should have been and sometimes one could see controls for the video that shouldn't have been there. I couldn't figure it out because when I would look at it in Ublock Origin's logging, it would suddenly start working. No matter the setting in Ublock or No Script, I couldn't get it to work right all the time. Here and there a video would display. I tried disabling all the extensions, but it never found 100% consistency.

Now I am doing a fresh install of Firefox from scratch and when I set up the https://gitcdn.xyz/cdn/NanoAdblocker/NanoFilters/0ebc3ac7250dfda9c7dfd93a0b272a2860056662/NanoFilters/NanoResources.txt in the advanced settings of Ublock Origin, suddenly it stopped working. I did all the other steps too, then disabled the extra filters. It was just the list. If I remove the txt link and put unset back, it works fine, but as soon as I add it, videos stop working.

Firefox 72.0.2 64 Bit, Latest Ublock Origin, instructions followed for setting up Nano Defender, and US location. It happens on any Daily Mail article that has the embedded videos, but not on the main Daily Mail page.

Thanks.

**Comment by jspenguin2017** [comment] 2020-01-24 01:47
For https://github.com/NanoMeow/QuickReports/issues/1616#issuecomment-577764311 : 
Works fine in Chrome, if this is a Firefox specific issue, report to the Firefox port maintainer. 
Also, don't pin the commit of the resource manifest, pull latest master instead.

**Comment by NanoMeow** [comment] 2020-04-10 14:58
### Basic Information

**Test link:** `https://www.dailymail.co.uk/news/article-8206121/Harvey-Weinstein-beats-coronavirus-released-quarantine-remains-suicide-watch.html`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12871.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.95 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

`PROMOTED` article (parasite streaming on hulu) on sidebar

this filter fixes: 
`dailymail.co.uk##.pufftext > .sponsored:nth-ancestor(3)`

**Comment by llacb47** [comment] 2020-04-10 15:12
or `dailymail.co.uk##.linkro-wocc.link-bogr2 > li:has(.sponsored)`
![image](https://user-images.githubusercontent.com/16567977/79001040-c654c880-7b1b-11ea-966e-f6025c62131e.png)

`dailymail.co.uk##.linkro-wocc.link-bogr2 > li:has(a[rel*="nofollow"])`
![image](https://user-images.githubusercontent.com/16567977/79001117-ee442c00-7b1b-11ea-99f4-005b1c215b06.png)

There are ads placeholders too, `dailymail.co.uk##.adHolder` would work but `dailymail.co.uk#@#.adHolder` is in uAssets...

**Comment by jspenguin2017** [comment] 2020-04-10 15:45
Those are not placeholders, they are actual ads. 

@okiehsch

**Comment by yourduskquibbles** [comment] 2020-04-10 15:45
> or `dailymail.co.uk##.linkro-wocc.link-bogr2 > li:has(.sponsored)`
> 
> `dailymail.co.uk##.linkro-wocc.link-bogr2 > li:has(a[rel*="nofollow"])`
> 


[`:nth-ancestor(n)`](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectnth-ancestorn) or newer syntax [`:updward(arg)`](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectnth-ancestorn) should be preferred over `has` and `has-text` filters as less computationally heavy

This is best option I think for majority of the sidebar ads coming through
`dailymail.co.uk##.pufftext > .sponsored:nth-ancestor(3)`
![image](https://user-images.githubusercontent.com/22258847/79003136-f00fee80-7b1f-11ea-8ef1-9d1c28815f86.png)

Thee's still one remaining one that isn't class `.sponsored` and this works for me, but maybe better option still? 
`dailymail.co.uk##.pufftext:has-text(/SPONSORED/):nth-ancestor(2)` 
![image](https://user-images.githubusercontent.com/22258847/79003022-b5a65180-7b1f-11ea-8794-0d869c85f574.png)

> There are ads placeholders too, `dailymail.co.uk##.adHolder` would work but `dailymail.co.uk#@#.adHolder` is in uAssets...

for empty ad holders
`dailymail.co.uk##.li.mpu_puff_wrapper`

![image](https://user-images.githubusercontent.com/22258847/79002906-7841c400-7b1f-11ea-8ed0-6ce261705ee8.png)

**Comment by llacb47** [comment] 2020-04-10 15:57
`dailymail.co.uk##.li.mpu_puff_wrapper` - `li` is not a class

![image](https://user-images.githubusercontent.com/16567977/79004225-50079480-7b22-11ea-86ad-9151948cd5d1.png)

This one is still there - enabled by `dailymail.co.uk#@#.billboard_wrapper` in uBlock filters

**Comment by yourduskquibbles** [comment] 2020-04-10 16:04
> `dailymail.co.uk##.li.mpu_puff_wrapper` - `li` is not a class

> This one is still there - enabled by `dailymail.co.uk#@#.billboard_wrapper` in uBlock filters

Good catch, should be fixed

**Closed** 2020-04-11 19:07 UTC
Labels: f: resolved, t: ads
