### ISSUE TITLE
pantagraph.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1455] opened 2019-07-04 01:14 UTC
### Basic Information

**Test link:** `https://www.pantagraph.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

### Additional Message

Additional site with same Anti-adblock: `https://columbustelegram.com/`

Part of lee enterprises Related #1449  just fixed `azdailysun.com` 

See `https://lee.net/markets/`

**Comment by okiehsch** [comment] 2019-07-04 01:49
Fixed.

**Comment by yourduskquibbles** [comment] 2019-07-08 12:58
Related: https://github.com/NanoMeow/QuickReports/issues/1449

This site is part of `Lee Enterprises` (List of market domains below from `https://lee.net/markets/`) and think the anti-adblock is on other domains with the same site template as well, tested by going to a few different articles on random domains and it pops up anti-adblock.

All Domains below:
```
auburnpub.com
azdailysun.com
beatricedailysun.com
billingsgazette.com
bismarcktribune.com
chippewa.com
columbustelegram.com
cumberlink.com
dailyjournalonline.com
democratherald.com
elkodaily.com
fremonttribune.com
gazettetimes.com
globegazette.com
hanfordsentinel.com
helenair.com
herald-review.com
jg-tc.com
journalstar.com
journaltimes.com
lacrossetribune.com
lompocrecord.com
madison.com
magicvalley.com
missoulian.com
mtstandard.com
muscatinejournal.com
napavalleyregister.com
nwitimes.com
pantagraph.com
poststar.com
qconline.com
qctimes.com
rapidcityjournal.com
ravallirepublic.com
santamariatimes.com
siouxcityjournal.com
stltoday.com
tdn.com
thesouthern.com
thetandd.com
theworldlink.com
trib.com
tucson.com
wcfcourier.com
winonadailynews.com
wiscnews.com
```
String of domain:
`auburnpub.com,azdailysun.com,beatricedailysun.com,billingsgazette.com,bismarcktribune.com,chippewa.com,columbustelegram.com,cumberlink.com,dailyjournalonline.com,democratherald.com,elkodaily.com,fremonttribune.com,gazettetimes.com,globegazette.com,hanfordsentinel.com,helenair.com,herald-review.com,jg-tc.com,journalstar.com,journaltimes.com,lacrossetribune.com,lompocrecord.com,madison.com,magicvalley.com,missoulian.com,mtstandard.com,muscatinejournal.com,napavalleyregister.com,nwitimes.com,pantagraph.com,poststar.com,qconline.com,qctimes.com,rapidcityjournal.com,ravallirepublic.com,santamariatimes.com,siouxcityjournal.com,stltoday.com,tdn.com,thesouthern.com,thetandd.com,theworldlink.com,trib.com,tucson.com,wcfcourier.com,winonadailynews.com,wiscnews.com`

**Comment by jspenguin2017** [comment] 2019-07-09 02:26
Eh... @okiehsch can you have a look? 😂

**Comment by okiehsch** [comment] 2019-07-09 02:34
I am in Europe this week so I am geo-blocked on those sites.

**Comment by okiehsch** [comment] 2019-07-09 02:58
If all sites have the same issue and removing the sites that are already part of `uBO-filters`.

````
@@||auburnpub.com^$generichide
@@||chippewa.com^$generichide
@@||cumberlink.com^$generichide
@@||dailyjournalonline.com^$generichide
@@||democratherald.com^$generichide
@@||elkodaily.com^$generichide
@@||fremonttribune.com^$generichide
@@||gazettetimes.com^$generichide
@@||globegazette.com^$generichide
@@||hanfordsentinel.com^$generichide
@@||herald-review.com^$generichide
@@||journaltimes.com^$generichide
@@||lompocrecord.com^$generichide
@@||mtstandard.com^$generichide
@@||muscatinejournal.com^$generichide
@@||qconline.com^$generichide
@@||ravallirepublic.com^$generichide
@@||santamariatimes.com^$generichide
@@||tdn.com^$generichide
@@||thetandd.com^$generichide
@@||theworldlink.com^$generichide
@@||winonadailynews.com^$generichide
@@||wiscnews.com^$generichide
||fundingchoicesmessages.google.com^$domain=auburnpub.com|chippewa.com|cumberlink.com|dailyjournalonline.com|democratherald.com|elkodaily.com|fremonttribune.com|gazettetimes.com|globegazette.com|hanfordsentinel.com|herald-review.com|journaltimes.com|lompocrecord.com|mtstandard.com|muscatinejournal.com|qconline.com|ravallirepublic.com|santamariatimes.com|tdn.com|thetandd.com|theworldlink.com|winonadailynews.com|wiscnews.com
auburnpub.com,chippewa.com,cumberlink.com,dailyjournalonline.com,democratherald.com,elkodaily.com,fremonttribune.com,gazettetimes.com,globegazette.com,hanfordsentinel.com,herald-review.com,journaltimes.com,lompocrecord.com,mtstandard.com,muscatinejournal.com,qconline.com,ravallirepublic.com,santamariatimes.com,tdn.com,thetandd.com,theworldlink.com,winonadailynews.com,wiscnews.com##.tnt-ads-container
````
should work but I would need somebody to verify that it actually does.

**Comment by yourduskquibbles** [comment] 2019-07-09 13:21
> 
> 
> If all sites have the same issue and removing the sites that are already part of `uBO-filters`.
> 
> ```
> @@||auburnpub.com^$generichide
> @@||chippewa.com^$generichide
> @@||cumberlink.com^$generichide
> @@||dailyjournalonline.com^$generichide
> @@||democratherald.com^$generichide
> @@||elkodaily.com^$generichide
> @@||fremonttribune.com^$generichide
> @@||gazettetimes.com^$generichide
> @@||globegazette.com^$generichide
> @@||hanfordsentinel.com^$generichide
> @@||herald-review.com^$generichide
> @@||journaltimes.com^$generichide
> @@||lompocrecord.com^$generichide
> @@||mtstandard.com^$generichide
> @@||muscatinejournal.com^$generichide
> @@||qconline.com^$generichide
> @@||ravallirepublic.com^$generichide
> @@||santamariatimes.com^$generichide
> @@||tdn.com^$generichide
> @@||thetandd.com^$generichide
> @@||theworldlink.com^$generichide
> @@||winonadailynews.com^$generichide
> @@||wiscnews.com^$generichide
> ||fundingchoicesmessages.google.com^$domain=auburnpub.com|chippewa.com|cumberlink.com|dailyjournalonline.com|democratherald.com|elkodaily.com|fremonttribune.com|gazettetimes.com|globegazette.com|hanfordsentinel.com|herald-review.com|journaltimes.com|lompocrecord.com|mtstandard.com|muscatinejournal.com|qconline.com|ravallirepublic.com|santamariatimes.com|tdn.com|thetandd.com|theworldlink.com|winonadailynews.com|wiscnews.com
> auburnpub.com,chippewa.com,cumberlink.com,dailyjournalonline.com,democratherald.com,elkodaily.com,fremonttribune.com,gazettetimes.com,globegazette.com,hanfordsentinel.com,herald-review.com,journaltimes.com,lompocrecord.com,mtstandard.com,muscatinejournal.com,qconline.com,ravallirepublic.com,santamariatimes.com,tdn.com,thetandd.com,theworldlink.com,winonadailynews.com,wiscnews.com##.tnt-ads-container
> ```
> 
> should work but I would need somebody to verify that it actually does.

@okiehsch I added your filters above and tested all domains by clicking on at least one article for each domain on a stock uBO profile. 

Your additional filters (plus existing uBO filters already in place) works for most sites but a few domains seem to still be triggering the anti-adblock modal popup: (Screenshot of one of the three I found below).

To recreate, you may need to click on the test link and then another article link from same domain to trigger the popup.

Test Link 1: `https://lacrossetribune.com/news/local/dark-la-crosse-stories-episode-the-pit-on-french-island/article_371577d4-14c5-57f6-becb-b82e2a24309a.html`

Test Link 2: `https://missoulian.com/news/local/density-concerns-v-affordable-housing-proposed-project-divides-city-council/article_ad15647b-4537-5b23-9423-dabe7c10161a.html`

Test Link 3: `https://napavalleyregister.com/news/local/customer-shocked-after-unlicensed-napa-roofer-left-beer-cans-on/article_cee02a39-b757-5960-af81-19ae46a71dd1.html`

![adblockmodal](https://user-images.githubusercontent.com/22258847/60890223-e07a1700-a228-11e9-85cb-ea4f1a02c682.png)


A few other domains have additional anti adblock footer overlay message - The dom element name for this is seemingly random so could be removed with a filter like `billingsgazette.com##div:has-text(You are seeing this message because ad or script blocking software is interfering with this page)` but not sure if that is preferred to just neutering the script checking for and generating this message.

Test Link 1: `https://beatricedailysun.com/news/world/asian-shares-mostly-retreat-ahead-of-fed-statement/article_33cf5a3b-4a6d-527d-8bd3-2211385915ad.html`

Test Link 2: `https://billingsgazette.com/news/state-and-regional/crime-and-courts/woman-sues-yellowstone-county-jail-after-suffering-incapacitating-injury/article_7e3fa9e5-6275-5c24-8e92-89642d3f111e.html`

Test Link 3: `https://bismarcktribune.com/news/local/bismarck/bismarck-state-college-gets-million-for-health-sciences-building/article_83f4d410-3ef5-5ed9-9ded-b574e37d4296.html`

Test Link 4: `https://helenair.com/news/state-and-regional/crime-and-courts/whitehall-man-dies-after-accidentally-shooting-self-at-helena-fairgrounds/article_5a02d1fc-cd86-5889-a7fb-d73c52dab4d1.html`

Test Link 5: `https://rapidcityjournal.com/news/local/state-and-regional/abortions-in-sd-down-in-significantly-lower-than-surrounding-states/article_0e3406a2-84f2-53e8-b8a3-d731dd603a36.html`

Test Link 6: `https://thesouthern.com/news/local/boycott-planned-over-du-quoin-state-fair-band-cancellation-amid/article_73aba4c7-9c3c-5a48-bf79-1094d3e0f909.html`

Test Link 7: `https://tucson.com/news/local/optics-are-bad-but-tucson-detention-center-a-great-idea/article_b5a578ad-f306-5610-b1ce-4ce8475540e6.html`

Screenshots of page as loaded:
![additionaladblock](https://user-images.githubusercontent.com/22258847/60890334-17502d00-a229-11e9-9cb4-cc9a739f2a5d.png)

Screenshot of page with anti-adblock element selected by element picker: 
![additionaladblock2](https://user-images.githubusercontent.com/22258847/60890340-1a4b1d80-a229-11e9-9bbd-ee77c932eab8.png)

Screenshot of page with inspector: 
![additionaladblock3](https://user-images.githubusercontent.com/22258847/60891075-98f48a80-a22a-11e9-8df7-3a9e16729afd.png)

**Comment by okiehsch** [comment] 2019-07-09 22:09
That commit should fix 

> Your additional filters (plus existing uBO filters already in place) works for most sites but a few domains seem to still be triggering the anti-adblock modal popup: (Screenshot of one of the three I found below).

For the other seven sites does adding 
````
@@||example.com^$generichide
example.com##.tnt-ads-container
````
work?

**Comment by yourduskquibbles** [comment] 2019-07-11 03:30
> @@||example.com^$generichide

Confirmed the 3 test links are fixed with https://github.com/uBlockOrigin/uAssets/commit/d6e9dcdbcfeb21841f05a7b0044bb615674b0194


Confirmed the 7 test links for the AAB footer banner is fixed with the following filters for me on a test profile
```
beatricedailysun.com,billingsgazette.com,bismarcktribune.com,helenair.com,rapidcityjournal.com,thesouthern.com,tucson.com##.tnt-ads-container
@@||beatricedailysun.com^$generichide
@@||billingsgazette.com^$generichide
@@||bismarcktribune.com^$generichide
@@||helenair.com^$generichide
@@||rapidcityjournal.com^$generichide
@@||thesouthern.com^$generichide
@@||tucson.com^$generichide
```

**Comment by okiehsch** [comment] 2019-07-11 04:40
Thanks. The issue should be fixed now.

**Closed** 2019-07-12 00:40 UTC
Labels: f: resolved, t: anti-adblock
