### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1751] opened 2019-08-31 00:16 UTC
### Basic Information

**Test link:** `https://www.wired.com/story/field-level-encryption-databases-mongobd/`
**Category:** other
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.56 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.124

### Additional Message

See: https://github.com/NanoMeow/QuickReports/issues/1396#issue-458289449

**Comment by jspenguin2017** [comment] 2019-08-31 00:17
Paywall shows even if I have no extensions enabled. Not sure if the wall is fake or not though.

**Comment by NanoMeow** [comment] 2019-10-19 17:29
### Basic Information

**Test link:** `https://www.wired.com/story/apple-china-censorship-apps-flag/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

detects private browsing mode

**Comment by jspenguin2017** [comment] 2019-10-19 19:41
For https://github.com/NanoMeow/QuickReports/issues/1751#issuecomment-544176845 : 
Out of scope as per instructions on the home page.

**Comment by NanoMeow** [comment] 2020-02-27 02:11
### Basic Information

**Test link:** `https://www.wired.com/story/covid-19-will-mark-the-end-of-affluence-politics/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4059.0 Safari/537.36 Edg/82.0.437.0
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

wired subscription ad breaks through 10 seconds after the page fully loads

**Comment by jspenguin2017** [comment] 2020-02-28 04:01
@okiehsch Page content glitches out, does not happen in guest mode. 
![image](https://user-images.githubusercontent.com/7283682/75509274-437d1180-59a4-11ea-827e-093ebe95b4e5.png)

**Comment by okiehsch** [comment] 2020-02-28 04:14
I can't reproduce in normal or guest mode.

**Comment by jspenguin2017** [comment] 2020-02-28 04:18
It works fine at first but breaks after about 10 seconds.

**Comment by okiehsch** [comment] 2020-02-28 04:27
![image](https://user-images.githubusercontent.com/16838044/75510334-ec4e5f80-59ea-11ea-97d0-c6b83dd4499d.png)

**Comment by okiehsch** [comment] 2020-02-28 04:30
Seems to depend on ones screen size.
I can reproduce if I zoom out. 
![image](https://user-images.githubusercontent.com/16838044/75510484-6f6fb580-59eb-11ea-94f9-9b26fd3afb1a.png)

**Comment by yourduskquibbles** [comment] 2020-02-28 13:49
https://github.com/NanoMeow/QuickReports/issues/1751#issuecomment-592302124 should be fixed in uBlock filters list now.

**Closed** 2020-02-29 04:17 UTC
Labels: f: resolved, t: breakage
