### ISSUE TITLE
mangaeden.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#113] opened 2018-09-21 00:33 UTC
### Basic Information

**Test link:** `https://www.mangaeden.com/en/en-manga/vampire-knight/87/1/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

### Additional Message

"Please disable adblock to continue" - notice appears, knows i am using ublock origin

**Comment by NanoMeow** [comment] 2018-11-06 19:48
### Basic Information

**Test link:** `https://www.mangaeden.com/it/it-manga/corpse-party-book-of-shadows/5/1/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.70

### Additional Message

**Comment by jspenguin2017** [comment] 2018-11-06 19:52
I can't reproduce any other problem beside a self-promotion. 

<details>

![image](https://user-images.githubusercontent.com/7283682/48089861-b3212900-e1c2-11e8-8f50-093ee74d75ae.png)

</details>

**Comment by NanoMeow** [comment] 2019-07-05 01:00
### Basic Information

**Test link:** `https://www.mangaeden.com/it/en-manga/cyborg-009/10/1/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170
**Extension:** Nano Defender 15.0.0.153

### Additional Message

**Comment by jspenguin2017** [comment] 2019-07-05 03:00
@okiehsch I see that this is fixed in the annoyance filter, but this is now a hard anti-adblock.

**Comment by okiehsch** [comment] 2019-07-05 03:41
Thanks, added to `uBO-filters`.

**Closed** 2019-07-05 04:31 UTC
Labels: s: backlog, s: dispatched, t: anti-adblock
