### ISSUE TITLE
jyra.online

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1618] opened 2019-08-03 07:12 UTC
### Basic Information

**Test link:** `https://jyra.online/cajun-popcorn-with-garlic-mayonnaise/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 OPR/62.0.3331.99
**Extension:** Nano Defender 15.0.0.157

**Comment by llacb47** [comment] 2019-08-03 18:03
Test links: `http://fc.lc/n7juEUf`, `http://fc.lc/9l0l1A`, `http://fc.lc/jKCxqeM`, and `http://fc.lc/iaewRlXh`.

Can't reproduce, it has been fixed in uAssets: https://github.com/uBlockOrigin/uAssets/commit/652889d497a3278595cf93da711587baa2c428f0

**Comment by jspenguin2017** [comment] 2019-08-03 21:11
Works fine for me.

**Comment by llacb47** [comment] 2019-08-03 21:18
Fake download button on `http://wi.cr/xBwZgO`: 
![Fake download button](https://user-images.githubusercontent.com/16567977/62416983-a37c2700-b612-11e9-94f2-9cc5656b9822.png)

`wi.cr##.banner-captcha.banner`

**Comment by jspenguin2017** [comment] 2019-08-03 21:21
@okiehsch

**Comment by okiehsch** [comment] 2019-08-04 01:45
Fixed.

**Closed** 2019-08-04 01:57 UTC
Labels: f: resolved, t: ads
